// export const LOGIN_WITH_GOOGLE_REQUEST = "LOGIN_WITH_GOOGLE_REQUEST"
// export const LOGIN_WITH_GOOGLE_SUCCESS = "LOGIN_WITH_GOOGLE_SUCCESS"
// export const LOGIN_WITH_GOOGLE_FAIL = "LOGIN_WITH_GOOGLE_FAIL"

// export const AUTH_WITH_GOOGLE_REQUEST = "AUTH_WITH_GOOGLE_REQUEST"
// export const AUTH_WITH_GOOGLE_SUCCESS = "AUTH_WITH_GOOGLE_SUCCESS"
// export const AUTH_WITH_GOOGLE_FAIL = "AUTH_WITH_GOOGLE_FAIL"

// export const USER_LOGIN_LOGOUT_REQUEST = "USER_LOGIN_LOGOUT_REQUEST"
// // 